spring:
  datasource:
    url: jdbc:postgresql://localhost:4433/musicdb
    username: postgres
    password: 0795225130
    generate-unique-name: false
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
aws:
  region: ap-east-1
  accessKey: AKIATMN2MSYEUJKMIIB2
  secretKey: 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
  s3:
    bucket:
      name: musicwebsite

server:
  port: 9000
security:
  jwt:
    secret-key: verysecretkeyohsosecretdamnhowlongisthispleasedontusethisinproduction
    token-duration: 1D